" Possibly redundant
set nocompatible
" Q normally switches to Ex mode, which I never want; use it for formatting instead.
map Q gq

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
  " make highlighted text black, so it shows up against yellow background
  highlight Search ctermfg=0
  " highlight Search ctermbg=7
  " highlight PreProc ctermfg=2 cterm=bold
  " make all the blues and reds bold, so you can actually read them.
  " highlight Comment cterm=bold
  " highlight SpecialKey cterm=bold
  " highlight Directory cterm=bold
  " highlight Type cterm=bold
  " highlight Statement cterm=bold
  " highlight Title cterm=bold
  " highlight Special cterm=bold
  " highlight PreProc cterm=bold
  " highlight Constant ctermfg=2
  " highlight Identifier ctermfg=6 cterm=bold
endif

" set t_kb=^?
fixdel

" source $VIMRUNTIME/vimrc_example.vim
behave xterm
set viewdir=~/.vim_view
set selectmode=mouse
set nobackup
set nowritebackup
set ruler
set autoindent
set expandtab
set textwidth=0
set backspace=indent,eol,start
set tabstop=4
set softtabstop=4
set shiftwidth=4
set nojoinspaces
set display=lastline
set linebreak
au BufRead * loadview
au BufWrite * mkview
au BufUnload * mkview

cabbrev h vert botright help
" cabbrev help vert botright help

" word-wrap text files, but not code
au BufRead,BufNewFile *.txt,*.tex,*.md,*.textile,*.markdown set lbr
" use tab chars in text and TeX files, but not markdown
au BufRead,BufNewFile *.txt,*.tex set noexpandtab
" TeX class files
au BufRead,BufNewFile *.cls set syntax=tex

" set statusline=%F%y%r%m%l,%c-%p
set showcmd

" move by visual line, not logical line
nmap j gj
nmap k gk

nmap <F1> 
imap <F1> 
nmap <F5> ?^[^ ]ma/^$kmb:'a,'bs/^	\(.*\)(.\{-\}\(\d*:\d\+)\)/  * \1(\2/
" imap <F5> ?^[^ ]ma/^$kmb:'a,'bs/^	\(.*\)(.\{-\}\(\d*:\d\+)\)/  * \1(\2/
nmap <F6> :r!date +"\%n\%n\%Y-\%m-\%d (\%A)\%n	\%-l:\%M\%P. "
" imap <F6> :r!date +"\%n\%n\%Y-\%m-\%d (\%A)\%n	\%-l:\%M\%P. "A
nmap <F7> :r!date +"	\%-l:\%M\%P. "
" imap <F7> :r!date +"	\%-l:\%M\%P. "A
nmap <F8> ?^\d\d\d\d-\d\d-\d\dma/^$kmb:'a,'b!~/dotfiles/summarize-time.py/^	TOTAL
" imap <F8> ?^\d\d\d\d-\d\d-\d\dma/^$kmb:'a,'b!~/dotfiles/summarize-time.py/^	TOTAL
nmap <F9> :,!fmt
" imap <F9> :,!fmtA

au BufRead,BufNewFile journal-personal.txt nmap <F6> :r!date +"\%n\%n\%Y-\%m-\%d \%-l:\%M:\%S \%p (\%A)\%n"
au BufRead,BufNewFile journal-personal.txt imap <F6> :r!date +"\%n\%n\%Y-\%m-\%d \%-l:\%M:\%S \%p (\%A)\%n"A
au BufRead,BufNewFile journal-*.tex nmap <F6> :r!date +"\%n\\subsection{\%A, \%B \\nth{\%-d}}\%n\\textbf{\%-l:\%M\%P}\%n"zz

call pathogen#infect()

au BufRead,BufNewFile *.html set tabstop=2 softtabstop=2 shiftwidth=2
" Disable Syntastic for Java
let g:syntastic_ignore_files = ['\m\c\.java$']

syntax enable
" set background=dark
set background=light
" colorscheme solarized

" au BufRead,BufNewFile journal-personal.txt highlight Normal cterm=bold ctermfg=1

au BufRead,BufNewFile *.go,Makefile set noexpandtab
au BufRead,BufNewFile *.clj set lisp tabstop=2 softtabstop=2 shiftwidth=2
au BufRead,BufNewFile *.clj filetype plugin indent on

set spell spelllang=en_us
" au BufRead,BufNewFile *.txt,*.tex,*.md,*.textile,*.markdown set spellcapcheck=  " don't check capitalization of first word in sentence
highlight clear SpellBad
highlight clear SpellLocal
highlight link SpellLocal SpellBad
" highlight SpellBad cterm=underline
highlight SpellBad ctermfg=1 guifg=Red
highlight clear htmlItalic
highlight htmlItalic ctermfg=4

set tags=./tags,tags

set nojoinspaces
" hide the toolbar in GVim
set guioptions-=T
