" Possibly redundant
set nocompatible
" Q normally switches to Ex mode, which I never want; use it for formatting instead.
map Q gq

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
  " highlight Search ctermbg=7
  " highlight PreProc ctermfg=2 cterm=bold
  " make all the blues and reds bold, so you can actually read them.
  " highlight Comment cterm=bold
  " highlight SpecialKey cterm=bold
  " highlight Directory cterm=bold
  " highlight Type cterm=bold
  " highlight Statement cterm=bold
  " highlight Title cterm=bold
  " highlight Special cterm=bold
  " highlight PreProc cterm=bold
  " highlight Constant ctermfg=2
  " highlight Identifier ctermfg=6 cterm=bold
endif

" set t_kb=^?
fixdel

" source $VIMRUNTIME/vimrc_example.vim
behave xterm
set viewdir=~/.vim_view
set selectmode=mouse
set nobackup
set nowritebackup
set ruler
set autoindent
set expandtab
set textwidth=0
set backspace=indent,eol,start
set tabstop=4
set softtabstop=4
set shiftwidth=4
au BufRead * loadview
au BufWrite * mkview
au BufUnload * mkview

au BufRead,BufNewFile *.hbs set filetype=html
au BufRead,BufNewFile *.txt so ~/Dropbox/config/.vim/txt.vim
au BufRead,BufNewFile *.jrn so ~/Dropbox/config/.vim/txt.vim
au BufRead,BufNewFile *.md,*.textile,*.markdown so ~/Dropbox/config/.vim/md.vim

" set statusline=%F%y%r%m%l,%c-%p
set showcmd

nmap <F1> 
imap <F1> 
nmap <F5> ?^[^ ]ma/^$kmb:'a,'bs/^	\(.*\)(.\{-\}\(\d*:\d\+)\)/  * \1(\2/
" imap <F5> ?^[^ ]ma/^$kmb:'a,'bs/^	\(.*\)(.\{-\}\(\d*:\d\+)\)/  * \1(\2/
nmap <F6> :r!date +"\%n\%n\%Y-\%m-\%d (\%A)\%n	\%-l:\%M\%P. "
" imap <F6> :r!date +"\%n\%n\%Y-\%m-\%d (\%A)\%n	\%-l:\%M\%P. "A
nmap <F7> :r!date +"	\%-l:\%M\%P. "
" imap <F7> :r!date +"	\%-l:\%M\%P. "A
nmap <F8> ?^\d\d\d\d-\d\d-\d\dma/^$kmb:'a,'b!~/dotfiles/summarize-time.py/^	TOTAL
" imap <F8> ?^\d\d\d\d-\d\d-\d\dma/^$kmb:'a,'b!~/Dropbox/config/summarize-time.py/^	TOTAL
nmap <F9> :,!fmt
" imap <F9> :,!fmtA

au BufRead,BufNewFile *.jrn nmap <F6> :r!date +"\%n\%n\%Y-\%m-\%d \%-l:\%M:\%S \%p (\%A)\%n	"A
au BufRead,BufNewFile *.jrn nmap <F7> :r!date +"\%n\%-l:\%M \%p\%n	"A
au BufRead,BufNewFile journal-personal.txt nmap <F6> :r!date +"\%n\%n\%Y-\%m-\%d \%-l:\%M:\%S \%p (\%A)\%n"
au BufRead,BufNewFile journal-personal.txt imap <F6> :r!date +"\%n\%n\%Y-\%m-\%d \%-l:\%M:\%S \%p (\%A)\%n"A

call pathogen#infect()

au BufRead,BufNewFile *.hbs,*.html set tabstop=2 softtabstop=2 shiftwidth=2
au BufRead,BufNewFile *.go set noexpandtab

syntax enable
" set background=dark
" colorscheme solarized

" au BufRead,BufNewFile journal-personal.txt highlight Normal cterm=bold ctermfg=1

highlight clear SpellBad
highlight SpellBad cterm=underline
highlight clear SpellLocal

set nojoinspaces
